<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SYN-FLX-005" name="scenarios.GEO.GeoTypePut" tests="15" failures="1" timestamp="17 Feb 2020 11:22:51 GMT" time="35.015" errors="0">
  <testcase name="TC_03" time="1.221" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_01" time="6.550" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_07" time="1.472" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_12" time="1.340" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_08" time="1.376" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_04" time="1.515" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_11" time="1.355" classname="scenarios.GEO.GeoTypePut">
    <failure type="java.lang.AssertionError" message="Test Failed">
      <![CDATA[java.lang.AssertionError: Test Failed
	at org.testng.Assert.fail(Assert.java:94)
	at scenarios.GEO.GeoTypePut.TC_11(GeoTypePut.java:1354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- TC_11 -->
  <testcase name="TC_14" time="1.290" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_10" time="1.437" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_13" time="9.812" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_15" time="2.038" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_02" time="1.257" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_05" time="1.465" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_09" time="1.527" classname="scenarios.GEO.GeoTypePut"/>
  <testcase name="TC_06" time="1.360" classname="scenarios.GEO.GeoTypePut"/>
</testsuite> <!-- scenarios.GEO.GeoTypePut -->
